### ISSUE TITLE
body数据库截取 

### ISSUE THREAD

**Issue by hupengtao** [dcblogdev/laravel-sent-emails#21]
[object] (PDOException(code: 22001): SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'body' at row 1

**Comment by dcblogdev** [comment]
publish the migrations if you haven't already and change the body from text to longtext that should be big enough for your needs, it will also be turning in compression in the config.

**Comment by dcblogdev** [comment]
I've added a new migration do a composer update and run migrations.

https://github.com/dcblogdev/laravel-sent-emails/pull/22
