### ISSUE TITLE
Lazy loading since 2.0.5

### ISSUE THREAD

**Issue by matejvelikonja** [dcblogdev/laravel-sent-emails#23]
Since the latest version, the page throws lazy loading issue.

**Comment by dcblogdev** [comment]
Can you provide more details on this issue?

**Comment by matejvelikonja** [comment]
I have configured Laravel to throw an error when lazy loading is detected. As a result, I'm encountering the following error with the newest version:

```
Attempted to lazy load [attachments] on model [Dcblogdev\LaravelSentEmails\Models\SentEmail] but lazy loading is disabled. (View: /xxx/vendor/dcblogdev/laravel-sent-emails/src/resources/views/index.blade.php)
```

I believe that a `with` statement should be added to [this line](https://github.com/dcblogdev/laravel-sent-emails/blob/master/src/Controllers/SentEmailsController.php#L15) in the `SentEmailsController` to load attachments together with emails. This will prevent n+1 query issues.

**Comment by dcblogdev** [comment]
thanks I've pushed a release that adds this in.
