### ISSUE TITLE
Add support for PHP 8.0

### ISSUE THREAD

**Issue by JonathanATyler** [dcblogdev/laravel-sent-emails#4]
Hi, love the package 👍 

I'd like to update my environment to test on PHP 8.0, but this is locked to ^7.2.
Can you add support for 8.0?

Cheers!

**Comment by dcblogdev** [comment]
Thanks, I've pushed a new release. I don't have PHP 8 installed to test on yet. Can you let me know how it goes?

**Comment by JonathanATyler** [comment]
Thanks for the quick update. No issues to report so far.

**Comment by dcblogdev** [comment]
Awesome, thanks for letting me know.
