### ISSUE TITLE
Improvement proposal

### ISSUE THREAD

**Issue by lengletremy** [dcblogdev/laravel-sent-emails#5]
Hello

Your package serves me to strengthen the security of my application by allowing my users to check the emails that the application sends to them, much like OVH can do. In this version unfortunately, if the user changes his email address, it is not possible to find all the emails that have been sent to him.
So I suggest you use morphs in your database.

https://laravel.com/docs/8.x/migrations#column-method-morphs

So we can still store the email address, but also which user received this email, even if the user profile is modified.

Sorry for my English, I'm French ;-)
Have a good day

**Comment by dcblogdev** [comment]
I don't plan on adding this but if you want to open a PR I'll accept it.
