### ISSUE TITLE
Suggestion : Display email attachments

### ISSUE THREAD

**Issue by Taoshan98** [dcblogdev/laravel-sent-emails#9]
Hi @dcblogdev , thanks for this package it is pretty cool and very easy to use!
I have a suggestion to implement, would it be feasible to show sent attachments in the email as well?
This way the package would be 100% complete!

Thanks again great job!

**Comment by RichieMcMullen** [comment]
I've added a feature to at least display the attachment count within the emails.

Pull request is active. Awaiting merge from owner.

**Comment by mtindall89** [comment]
this would be a great add - number of attachments or names of attachments

**Comment by dcblogdev** [comment]
Yes I'm working on an update which optionally stores attachments. When enabled attachments will be stored in a storage folder and a count displayed on the email list and download links shown on the email itself.

![CleanShot 2024-05-06 at 10 35 10@2x](https://github.com/dcblogdev/laravel-sent-emails/assets/1018170/f417f30c-0062-4e90-9cea-89098ca39bf0)
